In [3]:
from traceback import print_tb

import numpy as np

In [4]:
li = [1,2,3,4,5,6]
print(type(li))
print(li)
ar = np.array((1,2,3,4,5,6))
print(type(ar))
print(ar)

<class 'list'>
[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [6]:
li = [[1,2,3],[4,5,6]]
arr2D = np.array([[1,2,3],[4,5,6]])

In [7]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
import numpy as np

In [9]:
li = [1,2,3,4,5,6]
print(li)
print((type(li)))
ar = np.array(li)
print(ar)
print((type(ar)))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
for i in range(0,6):
    print(li[i])
    print(ar[i])

1
1
2
2
3
3
4
4
5
5
6
6


In [12]:
arr = np.array(range(0,10),ndmin=2)

In [13]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
arr.ndim

2

In [15]:
arr.shape

(1, 10)

In [16]:
# 2 represents rows,andd 5 repreent column
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2D.ndim

2

In [19]:
arr2D.shape

(2, 3)

In [21]:
arr2D = np.array(range(0,60)).reshape(2,3,2,5)

In [22]:
arr2D

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]],


       [[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [23]:
arr2D.shape

(2, 3, 2, 5)

In [25]:
print("*PytHon*")

*PytHon*


E

In [27]:
name=input("enter name: ")
clr=input("enter fav color")
print(f"Hi{name} your favorite color is {clr}")

Hiswaira your favorite color is black


In [28]:
import numpy as np

In [31]:
#arr1=np.arange(288).reshape(2,3,2,6,4)
arr1=np.array(range(288)).reshape(2,3,2,6,4)
print(arr1)

[[[[[  0   1   2   3]
    [  4   5   6   7]
    [  8   9  10  11]
    [ 12  13  14  15]
    [ 16  17  18  19]
    [ 20  21  22  23]]

   [[ 24  25  26  27]
    [ 28  29  30  31]
    [ 32  33  34  35]
    [ 36  37  38  39]
    [ 40  41  42  43]
    [ 44  45  46  47]]]


  [[[ 48  49  50  51]
    [ 52  53  54  55]
    [ 56  57  58  59]
    [ 60  61  62  63]
    [ 64  65  66  67]
    [ 68  69  70  71]]

   [[ 72  73  74  75]
    [ 76  77  78  79]
    [ 80  81  82  83]
    [ 84  85  86  87]
    [ 88  89  90  91]
    [ 92  93  94  95]]]


  [[[ 96  97  98  99]
    [100 101 102 103]
    [104 105 106 107]
    [108 109 110 111]
    [112 113 114 115]
    [116 117 118 119]]

   [[120 121 122 123]
    [124 125 126 127]
    [128 129 130 131]
    [132 133 134 135]
    [136 137 138 139]
    [140 141 142 143]]]]



 [[[[144 145 146 147]
    [148 149 150 151]
    [152 153 154 155]
    [156 157 158 159]
    [160 161 162 163]
    [164 165 166 167]]

   [[168 169 170 171]
    [172 173 174 175]
    [176 1

In [43]:
#indexing
print(arr1[1,1,1,0,-1])

219


In [50]:
print(arr1[0,0,0,0,1])

1


In [ ]:
#33

In [ ]:
#

In [69]:
slicingMatrix=np.array(range(60)).reshape(2,5,6)
li1=["a","b","c","d","e","f"]

In [58]:
li1[1:5] #after end range ratio index-1 before

['b', 'c', 'd', 'e']

In [59]:
slicingMatrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
slicingMatrix[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [64]:
slicingMatrix[3:5,4:6]

array([[22, 23],
       [28, 29]])

In [67]:
#previos of :2 as we initialize rows first
#if we write 2:4 it means from 2 index to 4-1 index
slicingMatrix[:2,2:4]

array([[2, 3],
       [8, 9]])

In [70]:
slicingMatrix

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [72]:
slicingMatrix[0,2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [73]:
slicingMatrix[0,2:4,2:4]
#medin, mode,like functions practice on your own end

array([[14, 15],
       [20, 21]])

In [74]:
slicingMatrix[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [75]:
slicingMatrix[0,1:3,1:4]

array([[ 7,  8,  9],
       [13, 14, 15]])

In [76]:
slicingMatrix[0,1:3,1:4:2]

array([[ 7,  9],
       [13, 15]])

In [ ]:
#csv (comma separated value cells like Excel) jason
#JSON API for communication (url for JSON)data type string key nad values
#api read response datatype string,  we have to typecast into dictionary


In [1]:
import numpy as np

In [3]:
tbt=np.array(([10,20,30,40]))

In [4]:
tbt

array([10, 20, 30, 40])

In [9]:
for i in tbt:
    print(i)

10
20
30
40


In [12]:
for i in tbt:
    if i>10 and i<40:
        print(i)
    else:
        continue

20
30


In [16]:
#filterring in array in numpy
arr= tbt[(tbt>10) & (tbt<40)]

In [17]:
arr

array([20, 30])

In [ ]:
#where command and .filter command for filtering in numpy
#array broadcasting do on yourself
