In [ ]:
#rows and columns data in 3D in large row
import numpy as np


In [ ]:
li=[1,2,3,4,5]
print(li)
print(type(li))
ar=np.array(li)
print(type(ar))
print(ar)
#array is faster tan lis 500 times or more as compare to list or other data structure
#timelit library use to measure time of a code

[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
#array intialization is not possible in python without numpy
arr=np.array((1,2,3,4,5))
print(type(arr))
print(arr/2)
#or pass list in the arguments
# arr1=np.array(li)
# print(arr1)

<class 'numpy.ndarray'>
[0.5 1.  1.5 2.  2.5]


In [ ]:
li2=[1,2,3,4,5]
#method 1
# for i in li2:
#     print(i*i)
#alternative for square
ar1=np.array(li)
#squara or if you want to perform any operation on array it will be impliment in each element in the array(directly perform on whole array an  its items)
print(ar1**2)
print(ar1+2)

1
4
9
16
25
[ 1  4  9 16 25]
[3 4 5 6 7]


In [ ]:
ar2=np.array(range(1,10))
print(ar2)
print(ar2.ndim)
ar2=np.array(range(1,10),ndmin=9)
print(ar2)
print(ar2.ndim)

[1 2 3 4 5 6 7 8 9]
1
[[[[[[[[[1 2 3 4 5 6 7 8 9]]]]]]]]]
9


In [ ]:
ar2D=np.array([[1,2,3],[4,5,6]])

In [ ]:
ar2D

array([[1, 2, 3],
       [4, 5, 6]])