In [2]:
#rows and columns data in 3D in large row
import numpy as np


In [4]:
li=[1,2,3,4,5]
print(li)
print(type(li))
ar=np.array(li)
print(type(ar))
print(ar)
#array is faster tan lis 500 times or more as compare to list or other data structure
#timelit library use to measure time of a code

[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
#array intialization is not possible in python without numpy
arr=np.array((1,2,3,4,5))
print(type(arr))
print(arr)
#or pass list in the arguments
arr1=np.array(li)
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[1 2 3 4 5]


In [9]:
li2=[1,2,3,4,5]
#method 1
# for i in li2:
#     print(i*i)
#alternative for square
ar1=np.array(li)
#squara or if you want to perform any operation on array it will be impliment in each element in the array(directly perform on whole array an  its items)
print(ar1**2)
print(ar1+2)

1
4
9
16
25
[ 1  4  9 16 25]
[3 4 5 6 7]
